services:
  database:
    image: postgres:16-alpine
    container_name: drupal_db
    environment:
      POSTGRES_DB: drupal_db
      POSTGRES_USER: drupal_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    restart: always

  drupal:
    image: drupal:latest
    container_name: drupal_web
    ports:
      - "8080:80"
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
    depends_on:
      - database
    restart: always

volumes:
  db_data:
